version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  database:
    driver: local

services:
  git:
    image: codeberg.org/forgejo/forgejo:10.0.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=$DB_TYPE
      - FORGEJO__database__HOST=$DB__HOST
      - FORGEJO__database__NAME=$DB_NAME
      - FORGEJO__database__USER=$DB__USER
      - FORGEJO__database__PASSWD=$DB__PASSWD
      - FORGEJO__actions__ENABLED=true
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /docker/backup:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 350M

  db:
    image: mysql:8
    container_name: gitea-db
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_USER=$DB__USER
      - MYSQL_PASSWORD=$DB__PASSWD
      - MYSQL_DATABASE=$DB_NAME
    networks:
      - gitea
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 350M
