version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  database:
    driver: local
  # runner:
  #   driver: local

services:
  git:
    image: gitea/gitea:1.20.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=$DB_TYPE
      - GITEA__database__HOST=$DB__HOST
      - GITEA__database__NAME=$DB_NAME
      - GITEA__database__USER=$DB__USER
      - GITEA__database__PASSWD=$DB__PASSWD
      - GITEA__actions__ENABLED=true
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
       - db
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 450M

  db:
    image: mysql:8
    container_name: gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_USER=$DB__USER
      - MYSQL_PASSWORD=$DB__PASSWD
      - MYSQL_DATABASE=$DB_NAME
    networks:
      - gitea
    volumes:
      - database:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 450M
  # ci:
  #   image: gitea/act_runner:latest
  #   container_name: gitea-runner
  #   environment:
  #     - GITEA_INSTANCE_URL=http://git:3000
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=$GITEA_RUNNER_TOKEN
  #     - GITEA_RUNNER_NAME=executor
  #   restart: always
  #   networks:
  #     - gitea
  #   volumes:
  #     - runner:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - git
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2.0'
  #         memory: 500M
