---
# code: language=ansible
- name: Start Certmanager
  hosts: proxmox
  tasks:
    - name: First Start
      import_role:
        name: certmanager
      vars:
        certmanager_goal: "start"

- name: Update Container
  hosts: container
  gather_facts: true
  tasks:
    - name: Ping Endpoints
      ansible.builtin.ping:
    - name: Update Systems
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
    - name: Update DNS block List
      ansible.builtin.command: pihole -up && pihole -g
      register: update_block_list
      changed_when: update_block_list.rc != 0
      when: ansible_facts['hostname'].startswith("pihole")
    - name: Restart Systems
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: ansible_facts['hostname'] != "wireguard" and ansible_facts['hostname'] != "monitor"
    - name: Restart Systems
      ansible.builtin.reboot:
        reboot_command: systemd-run reboot now
        reboot_timeout: 3600
      when: ansible_facts['hostname'] == "wireguard" or ansible_facts['hostname'] == "monitor"

- name: Update Observium
  hosts: monitor
  gather_facts: true
  tasks:
    - name: First Start
      import_role:
        name: observium

- name: Stop Certmanager
  hosts: proxmox
  tasks:
    - name: First Start
      import_role:
        name: certmanager
      vars:
        certmanager_goal: "stop"

- name: Update Portainer OCI
  hosts: portainer, portainer2, docker
  tasks:
    - name: Update standalone container
      include_role:
        name: portainer

- name: Update Hosts
  hosts: proxmox
  gather_facts: true
  become: false
  tasks:
    - name: Ping Endpoints
      ansible.builtin.ping:
    - name: Update Systems
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

- name: Reboot Host System
  hosts: proxmox
  gather_facts: true
  become: false
  tasks:
    - name: Ping Endpoints
      ansible.builtin.ping:
    - name: Restart Systems
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: ansible_run_tags == "reboot"
