---
- name: Update Container
  hosts: container
  gather_facts: true
  become: false
  tags: [update]
  tasks:
    - name: Ping Endpoints
      ansible.builtin.ping:
    - name: Update Systems
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
    - name: Update DNS block List
      ansible.builtin.command: pihole -up && pihole -g
      register: update_block_list
      changed_when: update_block_list.rc != 0
      when: ansible_facts['hostname'] == "pihole"
    - name: Restart Systems
      ansible.builtin.reboot:
        reboot_timeout: 3600

- name: Reboot Host System
  hosts: bare
  gather_facts: true
  tags: [reboot]
  become: false
  tasks:
    - name: Ping Endpoints
      ansible.builtin.ping:
    - name: Restart Systems
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: tag_name == "reboot"
