name: Run Ansible scripts for cert update
on:
  schedule:
    - cron: "0 20 1 * *"

jobs:
  run_test:
    name: run Cert update playbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          PRIV_KEY_pihole: ${{ secrets.PRIV_KEY_PIHOLE }}
          PRIV_KEY_docker: ${{ secrets.PRIV_KEY_DOCKER }}
          PRIV_KEY_monitor: ${{ secrets.PRIV_KEY_MONITOR }}
          PRIV_KEY_proxmox: ${{ secrets.PRIV_KEY_PROXMOX }}
          PRIV_KEY_wireguard: ${{ secrets.PRIV_KEY_WIREGUARD }}
          PRIV_KEY_certmanager: ${{ secrets.PRIV_KEY_CERTMANAGER }}
        run: bash keys/import.sh
      - run: apt update && apt install -y -q python3-pip && pip3 --version
      - run: pip3 install -r requirements.txt
      - run: ansible-playbook update_certs.yml -v --tags=update
