---
- name: Start cert manager container
  ansible.builtin.import_tasks: start.yml
  when: certmanager_goal == "start"

- name: Stop cert manager container
  ansible.builtin.import_tasks: stop.yml
  when: certmanager_goal == "stop"
