---
- name: Start container
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      pct start $( pct list | grep certmanager | tr -s ' ' | cut -d ' ' -f 1)
    executable: /bin/bash
  failed_when: false
  changed_when: true
- name: Sleep for 5 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 5
  delegate_to: localhost
- name: Check if container already running
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      pct status $( pct list | grep certmanager | tr -s ' ' | cut -d ' ' -f 1)
    executable: /bin/bash
  changed_when: false
  register: container_state
- name: Check if process run
  ansible.builtin.assert:
    that:
      - "'running' in container_state.stdout"
- name: Sleep for 5 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 5
  delegate_to: localhost
- name: Check if container is accessable
  ansible.builtin.ping:
  delegate_to: certmanager
